# Generated by Django 3.2.7 on 2021-11-01 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('midterms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choice',
        ),
    ]
